[project]
name = "analyse-nginx-logs"
version = "0.1.0"
description = "Скрипт для парсинга и анализа логов nginx"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.2.0",
    "structlog>=25.2.0",
]
